TIME_HOUR_UNIT = 24
TIME_MINUTE_UNIT = 60
TIME_SECOND_UNIT = 60
TIME_MILLIS_UNIT = 1000

LOTTERY_SCAN = 1
TRACEABILITY_SCAN = 2

WECHAT_USER_TYPE = 1

BATCH_DISCARD_STATUS = -1
BATCH_DONE_STATUS = 0
BATCH_PROCEEDING_STATUS = 1
BATCH_READY_STATUS = 2
BATCH_DOWNLOADING_STATUS = 3
BATCH_DOWNLOADED_STATUS = 4
